"""
AnalystState — LangGraph State Definition
==========================================
The single shared state object that flows through the entire graph.
Every node reads from and writes to this TypedDict.
"""

from typing import TypedDict, Optional, Literal


class AnalystState(TypedDict):
    """
    Shared state for the Text-to-SQL Analyst Agent graph.
    All fields are optional except `user_query` — nodes populate
    fields as the pipeline progresses.
    """

    # ── Input ──────────────────────────────────────────────────────────────
    user_query: str
    """The original natural language question from the user."""

    # ── Phase 1: Classification ────────────────────────────────────────────
    query_type: Optional[Literal["metadata", "data"]]
    """
    'metadata' → schema/definition question → routed to Metadata Resolver.
    'data'     → data retrieval question    → routed to Schema Selector → SQL pipeline.
    """

    classification_confidence: Optional[float]
    """Confidence score (0–1) from the classifier. Below 0.6 triggers clarification."""

    classification_reasoning: Optional[str]
    """Short explanation from the classifier LLM for why it chose the query_type."""

    # ── Phase 1: Schema Selection (data queries only) ──────────────────────
    selected_columns: Optional[list[dict]]
    """
    Top-k relevant columns from BigQuery similarity search.
    Each dict: {table_name, column_name, column_definition,
                column_type, column_data_type, column_metadata, sample_values, score}
    """

    selected_tables: Optional[list[str]]
    """Distinct table names derived from selected_columns."""

    relevant_joins: Optional[list[dict]]
    """
    Join conditions fetched from join_metadata for the selected tables.
    Each dict: {table_name_1, table_name_2, join_type, join_condition,
                column_list, sample_sql}
    """

    # ── Phase 2: SQL Generation & Execution ───────────────────────────────
    generated_sql: Optional[str]
    """The SQL query generated by GPT-5.1."""

    sql_error: Optional[str]
    """Error message from the last failed SQL execution attempt. None on success."""

    retry_count: Optional[int]
    """Number of SQL correction attempts so far. Max 3."""

    result_csv_path: Optional[str]
    """Absolute path to the CSV file written after successful SQL execution."""

    result_types_path: Optional[str]
    """Absolute path to the companion _types.json file for column dtype info."""

    row_count: Optional[int]
    """Number of rows returned by the SQL query."""

    column_names: Optional[list[str]]
    """Column names of the SQL result set."""

    # ── Phase 2: Error Handling ────────────────────────────────────────────
    error_stage: Optional[str]
    """The pipeline stage where an unrecoverable error occurred."""

    error_message: Optional[str]
    """User-facing error description."""

    is_error: Optional[bool]
    """True if the pipeline is in error/fallback mode."""

    # ── Phase 3: Sub-Agent Outputs ─────────────────────────────────────────
    analytical_response: Optional[str]
    """Detailed business analysis (5–6 bullets). Generated by the Response Sub-Agent."""

    insights_response: Optional[str]
    """Executive summary insights (5–6 bullets). Generated by the Response Sub-Agent."""

    visualization_json: Optional[str]
    """Plotly figure serialized as JSON string. None if visualization not applicable."""

    viz_chart_type: Optional[str]
    """Chart type chosen by the Visualizer Sub-Agent (e.g. 'bar', 'line', 'none')."""

    # ── Phase 1 (metadata path): Metadata Response ─────────────────────────
    metadata_response: Optional[str]
    """Natural language answer for metadata queries (schema questions)."""

    # ── Phase 4: Follow-Up ─────────────────────────────────────────────────
    follow_up_questions: Optional[list[str]]
    """3 suggested follow-up questions based on the current query."""

    # ── Final Output ───────────────────────────────────────────────────────
    final_response: Optional[str]
    """Assembled final response shown to the user in Gradio."""
